//tealium universal tag - utag.789 ut4.0.201603221728, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
$(function(){var $helpVideosTrigger,urls={'tabStory':'https://www.ancestry.com/academy/course/printing-out-your-lifestory-page?embed=true&playlist=lifestory-page-help&sidebar=true','tabFacts':'https://www.ancestry.com/academy/course/adding-a-web-link-to-your-facts-page?embed=true&playlist=facts-page-help&sidebar=true','tabGallery':'https://www.ancestry.com/academy/course/how-to-upload-a-photo-to-tree?embed=true&playlist=gallery-page-help&sidebar=true'};function getAncestryDomain(){var ancestryDomain='ancestry.com';try{ancestryDomain=utag.data['ut.domain'];}catch(e){}
return ancestryDomain;}
function showButtonIfOnCorrectTab(){if($('#tabStory.tabActive, #tabFacts.tabActive, #tabGallery.tabActive').length){$helpVideosTrigger.addClass('helpVideosLoaded');}else{$helpVideosTrigger.removeClass('helpVideosLoaded');}}
function openHelpVideos(){var url=urls[$('#personTabs').find('.tabActive').attr('id')];$('#helpVideos').html('<iframe id="helpVideo" src="'+url+'"></iframe>')}
$('head').append('<style>.helpModalHeader.helpModalHeader { line-height: inherit; } #helpVideosTrigger { bottom: -80px; position: fixed; right: 5px; -webkit-transition: bottom .5s ease-out; transition: bottom .5s ease-out; z-index: 1; } #helpVideosTrigger.helpVideosLoaded { bottom: 5px; } #helpVideos { margin:8px; position:relative; } #helpVideos::after { content:""; display:block; padding-bottom:46.11111% } #helpVideo { border:0; height:100%; left:0; position:absolute; top:0; width:100%; } @media (max-width:480px) { #helpVideos { margin:8px 0; } #helpVideos::after { padding-bottom:75%; } }</style>');$('body').append('<button class="ancBtn ancBtnRnd icon iconHelp silver ancBtnIconOnly480" id="helpVideosTrigger" title="Learn the basics with videos from Ancestry Academy." type="button">Tutorials</button>');$helpVideosTrigger=$('#helpVideosTrigger');$helpVideosTrigger.on('click',function(){$('<div class="modal">\
			<div class="modalHeader helpModalHeader">\
				<h4 class="modalTitle iconFlushText icon iconAcademy">Ancestry Academy Video Help <br><span class="normal">Check out these videos to learn how to manage people and relationships, enhance your ancestor’s story, and more.</span></span></h4>\
			</div>\
			<div id="helpVideos"></div>\
		</div>').modal({'showLoading':true,'useCustomPadding':true,'width':840,'onOpen':openHelpVideos});});setTimeout(function(){showButtonIfOnCorrectTab();$('#personTabs').on('click','.tab',showButtonIfOnCorrectTab);},1500);});}};utag.o[loader].loader.LOAD(id);})("789","ancestry.main");}catch(error){utag.DB(error);}
